### PR TITLE
Fix script name and revamp introductory comment

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
@rjfd For now, in the teuthology use case, I am going to do the following steps on the Salt Master node:

1. `git clone git://github.com/SUSE/DeepSea ; cd DeepSea`
2. install DeepSea (I will look in the README for how to do this)
3. `cd qa/`
4. `sh suites/basic-health-check.sh`

Correct?

**Comment by rjfd** [comment]
Correct

**Comment by smithfarm** [comment]
Thanks. By the way, you are totally welcome to squash these commits into yours and drop the commit messages, including the "Signed-off-by" lines!

**Comment by smithfarm** [comment]
Suggestions:

1. Put common code (SALT_MASTER and MINIONS_LIST definitions, run_stage() and gen_policy_cfg() functions) into a script - name might be something like `qa/common/dsit_common.sh` (?)
2. The SALT_MASTER and MINIONS_LIST environment variables defined at https://github.com/rjfd/DeepSea/blob/wip-teuthology-suite/qa/workunits/suites/basic-healt-ok.sh#L37-L41 could be prefixed with "DSIT_" (DeepSea Integration Test) and be exported.
3. Start `basic_health_ok.sh` with `source common/dsit_common.sh`
4. Make everything more verbose. After `export DSIT_SALT_MASTER=. . .` do `echo "DSIT_SALT_MASTER environment variable set to $DSIT_SALT_MASTER`, after generating policy.cfg do `echo "Generated the following policy.cfg:" ; cat policy.cfg` etc.

**Review by rjfd — APPROVED** [review]
LGTM

**Comment by rjfd** [comment]
@smithfarm your suggestions look great! I'll apply them ASAP

**Pull request merged**
